import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { ImprintComponent } from './imprint/imprint.component';   // generated by adding routes
import { PrivacyPolicyComponent } from './privacy-policy/privacy-policy.component';
import { SlideshowComponent } from './slideshow/slideshow.component'; // -"-

const routes: Routes = [
  { path: '', component: SlideshowComponent },  
  { path: 'imprint', component: ImprintComponent },  //ctr. space
  { path: 'privacy-policy', component: PrivacyPolicyComponent }  //ctr. space
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
